version: '3.9'

services:
  app:
    depends_on:
      - db
    build:
      context: .
      args:
        - DEV=true
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=maito_db
      - DB_USER=maito
      - DB_PASS=maitocode
      - DEBUG=1

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    volumes:
      - maito-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=maito_db
      - POSTGRES_USER=maito
      - POSTGRES_PASSWORD=maitocode

volumes:
  maito-db-data:
  pgadmin:
  dev-static-data: